### PR TITLE
Configures lando server to create, attach, and format volumes 

### LINKED ISSUE #49: Update server creation to attach and format a volume
While openstack volumes can be larger than 2TB, the root volume for an instance is limited to 2TB.

As of #44, the storage requirement is passed along to this parameter, but instances that boot won't have more than a 2TB partition because openstack requires their disklabel/partition type to be `mbr`.

So, to accommodate larger volume sizes we need to 

1. Create a volume
2. include that volume in shade's list of `volumes`
3. On boot, partition, format, and mount that volume.

We should allocate that storage to things that currently go in `/tmp` and `/data`. lando_worker uses `/data` for staging things in/out, and cwl/toil use `/tmp` though this can be overridden.

### PR DESCRIPTION
**Pull request by dleehr**
- Replaces BootScript with CloudConfigScript. cloud-config can place files and configure disks/filesystems/mounts
- JobActions.launch_vm now creates a volume, adds it to the cloud-config, and boots the instance with it attached
- CloudService.launch_instance now takes a list of volumes instead of a volume_size
- CloudService.terminate_instance takes a list of volume names to delete after terminating the instance
- Adds volume_mounts (dict) to VMSettings. Should be a dict of devices to mount points
- Expects jobs to have a vm_volume_name string field. Not yet implemented in bespin-api or lando-messaging

Fixes #49

### CODE REVIEW

**Comment by dleehr** [comment]
Will need to raise required version of lando messaging to 0.8.0 (https://github.com/Duke-GCB/lando-messaging/pull/10)

**Comment by johnbradley** [comment]
It looks like we are not passing vm_volume_name to `worker_client.stage_job`, `worker_client.run_job`, and `worker_client.store_job_output`. (https://github.com/Duke-GCB/lando/blob/partition-volumes/lando/server/lando.py#L160)
This is due to changes to `lando-messaging` here: https://github.com/Duke-GCB/lando-messaging/blob/master/lando_messaging/clients.py#L113

**Comment by johnbradley** [comment]
We need to revert the lando-messaging version in bespin-api https://github.com/Duke-GCB/bespin-api/blob/master/requirements.txt#L10.

**Comment by dleehr** [comment]
https://github.com/Duke-GCB/bespin-api/pull/58

**Pull request merged**
